version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./app:/app
    links:
      - php-fpm

  php-fpm:
    image: php7.1-fpm-memcached-3.0.3-mongo-1.4.1-mysql-postgresql
    volumes:
      - ./app:/app
    links:
      - mysql
      - mongo
      - memcached
      - postgresql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=test123
    ports:
      - 3306:3306
    volumes:
      - ./storages/mysql:/var/lib/mysql

  mongo:
    image: mongo:latest
    ports:
    - 27017:27017
    volumes:
    - ./storages/mongo:/data/db

  postgresql:
    image: postgres:10.3
    volumes:
      - ./storages/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=test123


  memcached:
    image: memcached:latest